version: '3.1'
services:

  app:
    build:
      context: .
    command: npm run start:dev
    volumes:
      - "./src:/app/src"
      - "./dev:/app/dev"
    ports:
      - "3025:3000"
      - "5858:5858"
    links:
      - mongo
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
    # environment:
    #   - SETUP_DEFAULT_USER=true

  mongo:
    image: mongo:3
    volumes:
      - ./.data/mongo:/data/db
    command: mongod --smallfiles --wiredTigerEngineConfigString='cache_size=512M'
    ports:
      - "27017:27017"
